### ISSUE TITLE
Get consultants by category not working

### ISSUE THREAD

**Issue by AviralJ58** [teampowstik/Powstik-Back#17]
Displaying all the consultants regardless of the category mentioned.

**Comment by akhilsrinivasp** [comment]
Multiple Categories are added using splitting of CSVs. So when you add "Diabetes, Weight Loss", these are considered two different categories. So instead you can use something like "Diabetes - Weight Loss"

**Comment by akhilsrinivasp** [comment]
Otherwise the functionality is good for the consultation part. I've checked it again
