### ISSUE TITLE
Standardize API Header Input

### ISSUE THREAD

**Issue by akhilsrinivasp** [teampowstik/Powstik-Back#29]
- Inputs for Categories are in CSV format and Output is in a list/array format. 
- Fix this by using standard list/array format.

**Comment by AviralJ58** [comment]
Input as comma separated will be convenient. For output, a list is returned as it can easily be traversed and individual categories can be displayed in frontend without expensive string split operations.

**Comment by akhilsrinivasp** [comment]
- For input, Front-End Dept will have to make the csv which will become a costly operation anyway. So, IMO this should be better to input a list. 
- Also if they send a csv we have to create a different type of delimiter.
